# Generated by Django 4.2.2 on 2023-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_datavisualization_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavisualization',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
    ]
