# Generated by Django 4.2.2 on 2023-06-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_datavisualization_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavisualization',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datavisualization',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datavisualization',
            name='relevance',
            field=models.IntegerField(null=True),
        ),
    ]
